### ISSUE TITLE
I run it with root role ,but not with --safe-perm option， But install success. Why

### ISSUE THREAD

**Issue by sunkuo** [kesla/node-snappy#111]
As we all known , if you install node-gyp-based package , you need run  "npm install xxx --unsafe-perm" if you logged as root .But  snappy does not need . Why , this really confused me !!!

**Comment by kesla** [comment]
I've never needed `--unsafe-perm` but I'm on Mac OS X so maybe this is a linux thing? Either way, sorry I can't help you on this.

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!
