### ISSUE TITLE
Failed on win10

### ISSUE THREAD

**Issue by Dollyn** [kesla/node-snappy#126]
C:\Windows\system32>npm install snappy  -g

> snappy@5.0.5 install C:\Users\sundl\AppData\Roaming\npm\node_modules\snappy
> node-gyp rebuild

C:\Users\sundl\AppData\Roaming\npm\node_modules\snappy>if not defined npm_config_node_gyp (node "D:\dev\nodejs\node\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  snappy-sinksource.cc
  snappy-stubs-internal.cc
  snappy.cc
c:\users\sundl\appdata\roaming\npm\node_modules\snappy\deps\snappy\snappy-1.1.2\snappy-stubs-internal.h : warning C4819
: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode for
mat to prevent data loss (compiling source file ......\deps\snappy\snappy-1.1.2\snappy.cc) [C:\Users\sundl\AppData\Ro
aming\npm\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
c:\users\sundl\appdata\roaming\npm\node_modules\snappy\deps\snappy\snappy-1.1.2\snappy-stubs-internal.h : warning C4819
: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode for
mat to prevent data loss (compiling source file ......\deps\snappy\snappy-1.1.2\snappy-stubs-internal.cc) [C:\Users\s
undl\AppData\Roaming\npm\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
  win_delay_load_hook.c
D:\dev\nodejs\node\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHo
ok2': redefinition; different type modifiers [C:\Users\sundl\AppData\Roaming\npm\node_modules\snappy\build\deps\snappy\
snappy.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\dev\nodejs\node\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\dev\nodejs\node\node.exe" "D:\dev\nodejs\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sundl\AppData\Roaming\npm\node_modules\snappy
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by Dollyn** [comment]
why don't you just provide a dll for windows users? it's ridiculous to have a node developer to install a huge vc builder.....

**Comment by kesla** [comment]
Hey @Dollyn.

> why don't you just provide a dll for windows users? it's ridiculous to have a node developer to install a huge vc builder.....

I'm not on Windows. I have no experience running node.js on Windows. Maybe that makes me arrogant but that's why we don't `just provide a dll for windows users`.

This is an open source project - so anyone can help out. If you're on Windows and have ideas for how to make it easier for windows users then *please help out*. Fork it, open a pull request or discuss here.

If you find this to ridiculous then just start your own project or something. Idk.

**Comment by kesla** [comment]
Either way, be positive. You give me no incentives to try and help you out with that tone.

**Comment by Dollyn** [comment]
For people that face the same problem and unfortunately know nothing about C/C++, here is an alternative: https://npm.taobao.org/package/snappyjs, pure js, no building needed, no gyp needed.

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!

**Comment by ben-burlingham** [comment]
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Foo\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
```
Hi @kesla, just a heads up, I've still got the original problem on Windows.  

I've installed Python and added to the PATH and installed `node-gyp -g`.  We'll probably move away from using Snappy but posting here so you're aware. :) Thanks for this package though!

**Comment by kesla** [comment]
@ben-burlingham Awesome!
