### ISSUE TITLE
Have you considered a Zstd version?

### ISSUE THREAD

**Issue by albertdb** [kesla/node-snappy#129]
Hi!

I was wondering if you have considered to develop a version of your library that uses Zstd compression format. Zstd is not as fast as Snappy but beats zlib by 20x while getting lower compressed sizes than zlib (both at default settings) and much lower sizes than Snappy, so it is a very interesting format to replace zlib in those cases Snappy doesn't compress enough.

Zstd interface doesn't seem very different from Snappy, so it shouldn't take very long to develop the binding.

I've started doing it myself using your code as a base, but I realized that my weak C++ skills are not enough for taking this anywhere.

Thank you very much,

Albert

**Comment by albertdb** [comment]
Issue body text written. Sorry for submitting it with empty body.

**Comment by kesla** [comment]
Hey,

I have not. There seem to exist some bindings already - https://github.com/x25/node-zstd - so I guess I'd go with using those bindings in case I need this type of compression.

I didn't know about zest, thanks for brining it to my attention!

**Comment by albertdb** [comment]
Unfortunately, that binding is obsolete. It uses the very first alpha version of zstd and even worse, it's not compatible with any version of Node >0.12. I've made and interface with the command line utility, but it's not the best approach.

**Comment by kesla** [comment]
@albertdb ok cool.

So, I'd be fine working on new bindings to zstd. It'd be fun. Was quite some time since I did any C++ work. But tbh, I'd be even more down to work with you getting the bindings working!

Do you have some WIP code that you can push for me to take a look at so I can try and help you with the missing pieces and getting it working? Or maybe there's some other way for us to work on these bindings together?

**Comment by albertdb** [comment]
Hi @kesla,

Sorry for the late reply, I was travelling. Unfortunately, all what I did regarding this is at work computer and I'm on holidays until the end of August. But, sincerely, I don't think it would be really useful to use it as a base.

I would like to participate in this, yet my C++ skills don't go over "C with classes", as I mentioned before. As you surely know, one thing is understanding code and a very different one is being able to write it :)

**Comment by kesla** [comment]
@albertdb oh, ok. Got it.

I'll try and take a look at zstd, I can't promise anything when I'll have bandwidth to create a module but it sounds like fun so perhaps it won't take too long ;)

**Comment by oaleynik** [comment]
@kesla just in case if you missed that - https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/?pnref=story

Facebook announced support of the Zstandard development ;)

**Comment by hex7c0** [comment]
👍
