### ISSUE TITLE
binding.node: invalid ELF header

### ISSUE THREAD

**Issue by meticulo3366** [kesla/node-snappy#130]
I have to ask, am I missing a system dependency in ubuntu? NPM installs successfully...

Running on docker container on ubuntu 14.04 LTS

node version 4

```
api_1                  | Unhandled Exception  [Error: /code/webapp/node_modules/my_module/node_modules/kafka-node/node_modules/snappy/build/Release/binding.node: invalid ELF header]  at time  Wed Jul 27 2016 18:34:51 GMT+0000 (UTC)
api_1                  | Error: /code/webapp/node_modules/my_module/node_modules/kafka-node/node_modules/snappy/build/Release/binding.node: invalid ELF header
api_1                  |     at Error (native)
api_1                  |     at Object.Module._extensions..node (module.js:460:18)
api_1                  |     at Module.load (module.js:356:32)
api_1                  |     at Function.Module._load (module.js:311:12)
api_1                  |     at Module.require (module.js:366:17)
api_1                  |     at require (module.js:385:17)
api_1                  |     at bindings (/code/webapp/node_modules/my_module/node_modules/kafka-node/node_modules/snappy/node_modules/bindings/bindings.js:76:44)
api_1                  |     at Object.<anonymous> (/code/webapp/node_modules/my_module/node_modules/kafka-node/node_modules/snappy/snappy.js:2:34)
api_1                  |     at Module._compile (module.js:435:26)
api_1                  |     at Object.Module._extensions..js (module.js:442:10)
api_1                  |     at Module.load (module.js:356:32)
api_1                  |     at Function.Module._load (module.js:311:12)
api_1                  |     at Module.require (module.js:366:17)
api_1                  |     at require (module.js:385:17)
api_1                  |     at Object.<anonymous> (/code/webapp/node_modules/my_module/node_modules/kafka-node/lib/codec/snappy.js:4:14)
api_1                  |     at Module._compile (module.js:435:26)
api_1                  |     at Object.Module._extensions..js (module.js:442:10)
api_1                  |     at Module.load (module.js:356:32)
api_1                  |     at Function.Module._load (module.js:311:12)
api_1                  |     at Module.require (module.js:366:17)
api_1                  |     at require (module.js:385:17)
api_1                  |     at Object.<anonymous> (/code/webapp/node_modules/my_module/node_modules/kafka-node/lib/codec/index.js:4:19)
api_1                  |     at Module._compile (module.js:435:26)
api_1                  |     at Object.Module._extensions..js (module.js:442:10)
api_1                  |     at Module.load (module.js:356:32)
api_1                  |     at Function.Module._load (module.js:311:12)
api_1                  |     at Module.require (module.js:366:17)
api_1                  |     at require (module.js:385:17)
api_1                  |     at Object.<anonymous> (/code/webapp/node_modules/my_module/node_modules/kafka-node/lib/client.js:11:16)
api_1                  |     at Module._compile (module.js:435:26)
api_1                  |     at Object.Module._extensions..js (module.js:442:10)
api_1                  |     at Module.load (module.js:356:32)
api_1                  |     at Function.Module._load (module.js:311:12)
api_1                  |     at Module.require (module.js:366:17)
api_1                  |     at require (module.js:385:17)
api_1                  |     at Object.<anonymous> (/code/webapp/node_modules/my_module/node_modules/kafka-node/lib/highLevelConsumer.js:6:14)
api_1                  |     at Module._compile (module.js:435:26)
api_1                  |     at Object.Module._extensions..js (module.js:442:10)
api_1                  |     at Module.load (module.js:356:32)
api_1                  |     at Function.Module._load (module.js:311:12)
```

npm install output is below

```
gyp info using node@4.2.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/install/node_modules/snappy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.2.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/install/node_modules/snappy',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/install/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/install/node_modules/snappy/build'
```

no issues installing but the application crashes due to a invalid ELF header, what is that?

**Comment by meticulo3366** [comment]
The solution to this problem is to install a system level library on ubuntu you must install `python-snappy`

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!

**Comment by lexi89** [comment]
Reopening. Still an issue on 6.3.4. 

`ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"/opt/nodejs/node_modules/snappy/build/Release/binding.node: invalid ELF header","stack":["Error: /opt/nodejs/node_modules/snappy/build/Release/binding.node: invalid ELF header","    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function.Module._load (internal/modules/cjs/loader.js:877:14)","    at Module.require (internal/modules/cjs/loader.js:1019:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at bindings (/opt/nodejs/node_modules/bindings/bindings.js:112:48)","    at Object.<anonymous> (/opt/nodejs/node_modules/snappy/snappy.js:2:34)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)"]}`

**Comment by harishshivaramegowda2020** [comment]
Facing below issue with 6.3.4: Any help here?

{"errorType":"Error","errorMessage":"/opt/nodejs/node_modules/snappy/build/Release/binding.node: invalid ELF header","trace":["Error: /opt/nodejs/node_modules/snappy/build/Release/binding.node: invalid ELF header","    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)","    at Module.load (internal/modules/cjs/loader.js:986:32)","    at Function.Module._load (internal/modules/cjs/loader.js:879:14)","    at Module.require (internal/modules/cjs/loader.js:1026:19)","    at require (internal/modules/cjs/helpers.js:72:18)","    at bindings (/opt/nodejs/node_modules/bindings/bindings.js:112:48)","    at Object.<anonymous> (/opt/nodejs/node_modules/snappy/snappy.js:1:34)","    at Module._compile (internal/modules/cjs/loader.js:1138:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)","    at Module.load (internal/modules/cjs/loader.js:986:32)"]}

**Comment by bbit8** [comment]
node_modules/snappy/build/Release/binding.node: invalid ELF header

same problem.

**Comment by matthew-valenti** [comment]
+1

**Comment by kungfutse** [comment]
Still occurs using 6.3.5 with node 12 in Docker

Error: /usr/app/node_modules/snappy/build/Release/binding.node: invalid ELF header
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at bindings (/usr/app/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/usr/app/node_modules/snappy/snappy.js:2:34)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
