### ISSUE TITLE
Question about thread

### ISSUE THREAD

**Issue by pierrre** [kesla/node-snappy#132]
Hello,
Does each call to `snappy.compress()` or `snappy.uncompress()` run in a dedicated "worker thread"?
Or do they all share the same thread?
Thank you.

**Comment by pranshu792** [comment]
Hello @pierrre ,
Nodejs runs c++ async tasks using threadpool ( via libeio & libev ), here the snappy binding is a async worker of c++. ( https://github.com/kesla/node-snappy/blob/master/src/binding.cc#L13 )
So, they dont use the same thread.

for more info on event loop: https://stackoverflow.com/a/11082422/2722603

**Comment by pierrre** [comment]
thank you :)
