### ISSUE TITLE
Snappy Build Issues

### ISSUE THREAD

**Issue by kidehen** [kesla/node-snappy#149]
node-gyp rebuild fails on my system. 
Log excerpt:

1799 error snappy@4.1.2 install: `node-gyp rebuild`
1799 error Exit status 1
1800 error Failed at the snappy@4.1.2 install script 'node-gyp rebuild'.
1800 error Make sure you have the latest version of node.js and npm installed.
1800 error If you do, this is most likely a problem with the snappy package,
1800 error not with npm itself.
1800 error Tell the author that this fails on your system:
1800 error     node-gyp rebuild
1800 error You can get information on how to open an issue for this project with:
1800 error     npm bugs snappy
1800 error Or if that isn't available, you can get their info via:
1800 error     npm owner ls snappy
1800 error There is likely additional logging output above.
1801 verbose exit [ 1, true ]

**Node version:** 6.11.3 for Mac OS X (El Capitan).

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!
