### ISSUE TITLE
Morally questionable test data

### ISSUE THREAD

**Issue by dcousens** [kesla/node-snappy#150]
In [`urls.10k`](https://github.com/kesla/node-snappy/blob/7896edda81bc0f82d76a414e7a6610571d6cdd9a/deps/snappy/snappy-1.1.4/testdata/urls.10K),  there are morally questionable URLs.

>  ... incestpornstories.com/cum-sex-pics/underagecoed/spankingsweating/hardendurance.html

Any reason?

**Comment by dcousens** [comment]
Nevermind,  they appear to come from upstream...
https://github.com/google/snappy/blob/master/testdata/urls.10K

**Comment by dcousens** [comment]
@pwnall ?

**Comment by sesse** [comment]
Hi,

I don't work for Google anymore, and I don't work with Snappy. But these did indeed come from upstream, way back before Snappy was open-sourced. As far as I know, they're simply a random sample of URLs from Google's crawler at some point. If you are offended by the existence of such URLs in the test data, you'll have to file an upstream bug to get the dataset cleaned (I doubt it would mean too much for the compression characteristics of the set).
