### ISSUE TITLE
Snappy build issues on Windows 10

### ISSUE THREAD

**Issue by indrajithpatelrsap** [kesla/node-snappy#154]
Hi ,

I get an error when i try to install snappy in windows.

Current node version : 8.11.1
npm : 6.0.0

C:\Users\I328838\git\dummy-kafka-forwarder1\node_modules\snappy>if not defined npm_config_node_gyp (node "C:\Users\I328838\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\I328838\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build to
ols, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\
Users\I328838\git\dummy-kafka-forwarder1\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\I328838\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\I328838\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\I328838\git\dummy-kafka-forwarder1\node_modules\snappy
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN kafka-forwarder@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snappy@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I328838\AppData\Roaming\npm-cache\_logs\2018-05-10T06_25_59_319Z-debug.log

Can anyone please help me with this. I have MSVS 2013 as well as 2015 installed in my machine. 

@kesla Could you kindly help me with this

Thanks and regards
Indrajith

**Comment by kesla** [comment]
I don't know anything about windows 10 so I can't help you really.

But looking at the error there's a suggestion you need to install or update build tools.

```
The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build to
ols, please install v140 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution.
```

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!
