### ISSUE TITLE
Bump nan

### ISSUE THREAD

**Issue by stephenh** [kesla/node-snappy#163]
Not a big deal, but I got this build error when installing with node v10:

https://github.com/nodejs/nan/issues/766

I switched to node v8 for what I was doing to unblock, but AFAIU from that issue, just bumping node-snappy's version of nan should get node v10 support for free-ish. Haven't actually tried it and I'm not an expert on node native modules, so apologies if I'm missing something.

**Comment by kesla** [comment]
Hey,

We should be supporting node v10 and we are using the latest version of nan.

Are you using the latest version of snappy?

**Comment by stephenh** [comment]
Oh right; I was using another project that transitively pulled in snappy. Should have thought of that. Thanks!
