### ISSUE TITLE
fail on windows with iojs

### ISSUE THREAD

**Issue by hex7c0** [kesla/node-snappy#42]
I don't know if an issue related with appveyor or c++ source code

[master branch](https://ci.appveyor.com/project/kesla/node-snappy/build/1.0.4/job/f3b29c80otc3t7qq)
[restyling branch](https://ci.appveyor.com/project/kesla/node-snappy/build/1.0.6/job/dblj5gujrgiw4a30)

on linux works perfectly

**Comment by kkoopa** [comment]
Known issue. Run with iojs and it works.

https://github.com/iojs/io.js/issues/751

**Comment by hex7c0** [comment]
thanks :+1:
