### ISSUE TITLE
error: invalid conversion from ‘v8::Value*’ to ‘v8::Object*’ [-fpermissive]

### ISSUE THREAD

**Issue by MichielDeMey** [kesla/node-snappy#43]
Any idea what's causing this?

```
CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from /tmp/.node-gyp/0.8.28/src/node.h:62:0,
                 from ../src/./binding.h:23,
                 from ../src/binding.cc:21:
/tmp/.node-gyp/0.8.28/deps/v8/include/v8.h: In constructor ‘v8::Handle<T>::Handle(v8::Handle<S>) [with S = v8::Value, T = v8::Object]’:
../src/binding.cc:113:38:   instantiated from here
/tmp/.node-gyp/0.8.28/deps/v8/include/v8.h:202:5: error: invalid conversion from ‘v8::Value*’ to ‘v8::Object*’ [-fpermissive]
make: *** [Release/obj.target/binding/src/binding.o] Error 1
```

I'm running node 0.8.28 on Linux.

**Comment by kkoopa** [comment]
https://github.com/kesla/node-snappy/blob/master/src/binding.cc#L110
`v8::Local<v8::Value> res;` should be `v8::Local<v8::Object> res;`

**Comment by MichielDeMey** [comment]
Will this get pushed to master and tagged as a new release?

Thanks for the quick reply!

**Comment by kesla** [comment]
I thought (based on #37) that node 0.8 wasn't supported anymore in NAN and that we therefore couldn't support it here anymore and still be compatible with iojs.

I've pushed a branch and will see if I can get the tests passing on node 0.8, @MichielDeMey I'll keep you posted!

**Comment by kkoopa** [comment]
That is incorrect. 0.8 still works, but 0.6 does not compile any longer.

**Comment by kkoopa** [comment]
And the correct fix is not changing https://github.com/kesla/node-snappy/blob/master/src/binding.cc#L110 but changing https://github.com/kesla/node-snappy/blob/master/src/binding.cc#L113
from `memcpy(node::Buffer::Data(res), dst.c_str(), dst.length());` to `memcpy(node::Buffer::Data(res.As<Object>()), dst.c_str(), dst.length());`

**Comment by kesla** [comment]
@kkoopa thanks! You're the man!

**Comment by kesla** [comment]
also #44

**Comment by kesla** [comment]
@MichielDeMey node 0.8 is supported again as of v3.0.7 that I just published!

**Comment by MichielDeMey** [comment]
Thanks @kesla and @kkoopa!
Feel free to close this issue. :)
