### ISSUE TITLE
Compatibility Issue on Stream v. Raw?

### ISSUE THREAD

**Issue by kevinmeredith** [kesla/node-snappy#46]
I've used java snappy library at https://github.com/xerial/snappy-java for compression.

Its [README](https://github.com/xerial/snappy-java#compatibility-notes) notes a compatibility issue of raw v. streams when compressing documents:

>SnappyOutputStream and SnappyInputStream use [magic header:16 bytes]([block size:int32][compressed data:byte array])* format. You can read the result of Snappy.compress with SnappyInputStream, but you cannot read the compressed data generated by SnappyOutputStream with Snappy.uncompress.

With a Snappy compressed file, via the Stream way, I checked if it had been compressed:

```
var snappy = require('snappy');
var fs     = require('fs');

var filename = './snappy_compressed_docs/snappy_compressed_file'

fs.readFile(filename, 'utf8', function(err, data) {
    if (err) throw err;    
    console.log("done printing data. 'typeof data':", typeof data);

    console.log("snappy: ", snappy);

        snappy.isValidCompressed(data, function(e, result) {
        if(e) { console.log("error!", e); throw e; }
            console.log("snappy.isValidCompressed:", result);
    });
});
```

But the output was **false**. 

Does this library have any compatibility issues/notes that's similar to the Java library?

**Comment by kesla** [comment]
Yes. The streaming snappy format and the normal snappy format aren't compatible.

**Comment by kevinmeredith** [comment]
Thanks
