### ISSUE TITLE
node-gyp rebuild failure

### ISSUE THREAD

**Issue by dhirajpraj** [kesla/node-snappy#48]
Hi,
I am facing some problem while installing one nodejs module called kafka-node. It seems like it has dependency on snappy which is failing.

Platform is Centos: Linux vm-a055 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Node version: v0.12.0

npm version: 2.5.1

python version: 2.6.6

error logs:

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/deploy/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-504.1.3.el6.x86_64
gyp ERR! command "node" "/home/deploy/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/deploy/AnalyticsWithNodeJS/node_modules/kafka-node/node_modules/snappy
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.1.3.el6.x86_64
npm ERR! argv "/home/deploy/node-v0.12.0-linux-x64/bin/node" "/home/deploy/node-v0.12.0-linux-x64/bin/npm" "install" "kafka-node"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! snappy@3.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@3.0.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

Could you please help us out. Please let me know in case you need any other information.

**Comment by xiaofengxiandeqingren** [comment]
Have you solve this problem.i came across the same problem,and i do not kown how to deal with it

**Comment by dhirajpraj** [comment]
Not yet solved

**Comment by kesla** [comment]
Hey sorry for not getting back earlier.

I don't know centos - but you error message looks a little bit like the errors in https://github.com/rvagg/node-levelup/issues/224 - so perhaps read through and follow the steps others took in there?

**Comment by kesla** [comment]
any luck?

**Comment by dhirajpraj** [comment]
Installing gcc did the trick for me. Thanks

**Comment by unbalanced** [comment]
Hey
Which commad did you use to install gcc
And which version of gcc?
Thanks

**Comment by dhirajpraj** [comment]
I don't remember the command or the version. Try installing the latest one.
The command should be easy to google.
