### ISSUE TITLE
recent changes to gyp (--no-parallel) breaks snappy build on ubuntu 14.4

### ISSUE THREAD

**Issue by GitaWei** [kesla/node-snappy#56]
commenting out the --no-parallel in the gyp/pangyp stuff fixes the build, but it appears snappy should be updated to support this.  Perhaps this is a gyp issue, but other packages seem to be rebuilding fine.
Note: this is not an issue with the node cmd being nodejs on ubuntu as the bottom of the error msg staes.

> snappy@3.2.0 install /home/ldavison/node-snappy
> pangyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/ldavison/node-snappy/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "node" "/home/ldavison/node-snappy/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /home/ldavison/node-snappy
gyp ERR! node -v v0.10.25
gyp ERR! pangyp -v v2.2.0
gyp ERR! not ok 
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by kesla** [comment]
Hey @GitaWei!

This is a bug in node-gyp, see https://github.com/TooTallNate/node-gyp/issues/426.
