### ISSUE TITLE
Build issues on different platforms

### ISSUE THREAD

**Issue by macobo** [kesla/node-snappy#59]
Snappy (used by node-kafka) causes troubles for projects with checked in `node_modules` due to elf header errors. 

These sorts of problems mitigated by including pre-built binaries in the package, similar to what [node-sass](https://github.com/sass/node-sass#rebuilding-binaries) does.

**Comment by kesla** [comment]
Hey, terribly sorry about that - this has now been fixed.

I released a v `3.2.2` that's the same as `3.2.0` while the old `3.2.1` is now version `4.0.0` instead!

**Comment by macobo** [comment]
This is about a different issue than the nan version fixing.

When running running code from a project which has `node_modules` checked in and kafka-node installed under osx, I get `Error: /home/macobo/projects/heap/node_modules/kafka-node/node_modules/snappy/build/Release/binding.node: invalid ELF header` under linux. This is reasonable given the different platforms building the c code, but very annoying to put up with.

A way around this is to do what `node-sass` does (link in the first comment) and bundle different binaries in npm.

**Comment by kesla** [comment]
oh right.

You can do `npm rebuild` to get the correct binaries. Other than that I'd gladly accept a PR with pre-build binaries!

**Comment by Sneagan** [comment]
`npm rebuild snappy` is not resolving this issue for me. I'm running in a Docker container using Centos 7 and the rebuild is completing without error.

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!
