### ISSUE TITLE
version 3.2.0 removed from npm servers

### ISSUE THREAD

**Issue by sbisbee** [kesla/node-snappy#60]
Hello -

Our builds started failing today for both our packages and our dependency's installs because version 3.2.0 of snappy isn't available on npm anymore. Was there a reason for its removal?

Depending on the reason, could you please add it back? Our internal packages are easy to update, but then we have to version our dependencies.

Cheers,
Sam

**Comment by kesla** [comment]
@sbisbee hey sorry that was a mistake from my POV - I was trying to fix another issue and wanted to unpublish v3.2.1 but wrote the wrong version...

npm doesn't allow you to republish something that you've unpublished, so you'll need to update and use v3.2.2 (that's identical to 3.2.0) instead. Sorry for the inconvenience.

**Comment by sbisbee** [comment]
@kesla Alright, thank you for the update. We'll figure out a way to get 3.2.2 in everywhere - good to hear it's the same as 3.2.0.

We'll chalk The Real Bug up to npm allowing package deletions. heh

Cheers.
