### ISSUE TITLE
kafka-node installation

### ISSUE THREAD

**Issue by iamvamshi** [kesla/node-snappy#65]
Hi,

I'm getting the below error while trying to install Kafka-node.Could you please help me out of these.

C:\Windows\system32>npm install -g kafka-node
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
\

> snappy@3.2.2 install C:\Users\vamshi\AppData\Roaming\npm\node_modules\kafka-no
> de\node_modules\snappy
> pangyp rebuild

gyp: C:\Users\vamshi.node-gyp\0.12.7\common.gypi not found (cwd: C:\Users\vamsh
i\AppData\Roaming\npm\node_modules\kafka-node\node_modules\snappy) while reading
 includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\vamshi\AppData\Roaming\npm
\node_modules\kafka-node\node_modules\snappy\node_modules\pangyp\lib\configure.j
s:346:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\vamshi\AppData\Roaming\npm\node_modules\
\kafka-node\node_modules\snappy\node_modules\pangyp\bin\node-gyp.js" "rebu
ild"
gyp ERR! cwd C:\Users\vamshi\AppData\Roaming\npm\node_modules\kafka-node\node_mo
dules\snappy
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "kafka-node"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! snappy@3.2.2 install: `pangyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@3.2.2 install script 'pangyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

Thanks for your reply in advance

![error](https://cloud.githubusercontent.com/assets/14195757/9757458/5e5f97d2-56fe-11e5-89ba-b2a595267167.png)

**Comment by obazoud** [comment]
Hi,

I can not install kafka-node, an error occurs on snappy installation

```
> snappy@3.2.2 install /opt/xxx/node_modules/kafka-node/node_modules/snappy
> pangyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/xxxx/node_modules/kafka-node/node_modules/snappy/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:296:17)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "node" "/opt/xxx/node_modules/kafka-node/node_modules/snappy/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /opt/xxx/node_modules/kafka-node/node_modules/snappy
gyp ERR! node -v v0.10.40
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
```

**Comment by janantala** [comment]
I am getting this error inside latest node v4.0.0 docker container

```
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! snappy@3.2.2 install: `pangyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@3.2.2 install script 'pangyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! pangyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls snappy
npm ERR! There is likely additional logging output above.
```

**Comment by itga** [comment]
I found this from node-gyp and it helps me.

https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup

Perhaps, node-gyp only works with python2 and MS Visual Studio (C++) 2010

**Comment by kesla** [comment]
@iamvamshi @obazoud @janantala Hey, seem you experienced a few different problems with building this module... Any progress or anything I can help with? As mentioned in https://github.com/kesla/node-snappy/issues/77 - you need a build toolchain on your machine for this to work.

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!
