### ISSUE TITLE
Node - 4.1.2 Support - npm install snappy installation error

### ISSUE THREAD

**Issue by sunnyfrancis** [kesla/node-snappy#77]
Hi,
I am unable install snappy on node version 4.1.2 and getting below error:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/appserver/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.5.1.el6.x86_64
gyp ERR! command "/appserver/node/bin/node" "/appserver/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cloud/services/service-masterdata/v1.0.0/node_modules/snappy
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-431.5.1.el6.x86_64
npm ERR! argv "/appserver/node/bin/node" "/appserver/node/bin/npm" "install" "kafka-node"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

Kindly help with this.

**Comment by kesla** [comment]
What OS are you on? Can you install other compiled modules? Thanks

**Comment by sunnyfrancis** [comment]
I am on Linux server -2.6.32-431.5.1.el6.x86_64

**Comment by kesla** [comment]
@sunnyfrancis Can you install other complied modules - for example leveldown? https://www.npmjs.com/package/leveldown

**Comment by daveroberts** [comment]
This problem is occurring for me again.  I cannot install leveldown as well.

**Comment by eliquious** [comment]
I'm also seeing this on OSX Yosemite with Node v4.2.1.

Here's a little more from the error:

```
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
```

**Comment by kesla** [comment]
@eliquious You need a build toolchain for snappy to work, on OSX it seem that `xcode-select --install` might fix it (https://github.com/lovell/sharp/issues/80). I'm on OSX Yosemite myself and node 4.x and I've been able to run this without any problems.

**Comment by kesla** [comment]
@sunnyfrancis @daveroberts Did you figure out a solution for this? Do you have a build toolchain installed on your machine?

I had to configure travis to use clang as the compiler to make it work (https://github.com/kesla/node-snappy/blob/master/.travis.yml#L1-L2), is that helpful?

**Comment by kesla** [comment]
cc @d00rman who reported issues with snappy in https://github.com/wikimedia/restevent/pull/3

**Comment by respect77** [comment]
hi i can't install snappy@4.0.5..
thanks

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/xx/node_modules/snappy
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "snappy"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! snappy@4.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@4.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

**Comment by respect77** [comment]
hi I can't install snappy 4.0.5..
thanks
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/xx/node_modules/snappy
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "snappy"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! snappy@4.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@4.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

**Comment by robey** [comment]
this is happening for me, too. i can't find a version of snappy that works -- tried 4.0.0 through 4.0.5 inclusive. 4.0.0 has some gyp-related error, but the rest are assuming gcc exists on a yosemite mac:

```
> node-gyp rebuild

  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kesla** [comment]
@robey I am on Mac OS X, with xcode installed I've never had a problem installing snappy. Do you have xcode installed & therefore gcc installed? Since snappy is a compiled dependency that's a requirement for snappy to work.

**Comment by robey** [comment]
I finally tracked this down and came up with a workaround: node 4.2 now requires xcode 7. The error message comes from using xcode 6 (which is what comes with Yosemite).

xcode 7 will not update via App Store "updates", nor can you update it from the command-line. You need to manually install the full 4.5GB package from the App Store as if it were a new app. Afterwards, rebuild every native node package.

This is a terrible experience, but it's really a bug with node, not snappy. I'm posting this here in case it helps anyone else.

**Comment by pdamyan** [comment]
I'm running into this issue as well. I was able to install leveldown but can't install snappy. Its a RHEL 6 server.

**Comment by esatterwhite** [comment]
I have this problem as well on linux w/ node 4.4. Can install other compiled modules. Can install leveldown

```
make: Entering directory '/home/esatterwhite/dev/js/kafka-playground/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
ar: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/libLLVM-3.8.so)

/bin/sh: line 1: 27513 Segmentation fault      (core dumped) ar crs Release/obj.target/deps/snappy/snappy.a Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
deps/snappy/snappy.target.mk:126: recipe for target 'Release/obj.target/deps/snappy/snappy.a' failed
make: *** [Release/obj.target/deps/snappy/snappy.a] Error 139
make: Leaving directory '/home/esatterwhite/dev/js/kafka-playground/node_modules/snappy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/esatterwhite/.nvm/versions/node/v4.4.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.3-2-ARCH
gyp ERR! command "/home/esatterwhite/.nvm/versions/node/v4.4.1/bin/node" "/home/esatterwhite/.nvm/versions/node/v4.4.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/esatterwhite/dev/js/kafka-playground/node_modules/snappy
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Linux 4.3.3-2-ARCH
npm ERR! argv "/home/esatterwhite/.nvm/versions/node/v4.4.1/bin/node" "/home/esatterwhite/.nvm/versions/node/v4.4.1/bin/npm" "install" "snappy" "--save"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! snappy@5.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@5.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snappy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

```

**Comment by johnshumon** [comment]
@esatterwhite What version of python and glibc are you using? I took me two days to figure out right versions. Type following command:
```
python -V
yum info glibc (if you are using centos/redhat)
```

> python 2.7.x and GLIBC_2.14

 or higher is needed to install snappy.

I had the exact build error. when I updated those, then it worked fine. My system configuration below:
```
OS: CentOS Linux release 7.2.1511 (Core)
glibc: 2.17
python: 2.7.5
node: v4.4.7
npm: 2.15.8
```

After that issuing

>  npm instal

l worked fine for me. Output below:
```
npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/
> dtrace-provider@0.6.0 install /home/tecnotree/sftp-invoice-uploader/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> snappy@4.1.2 install /home/tecnotree/sftp-invoice-uploader/node_modules/kafka-node/node_modules/snappy
> node-gyp rebuild

make: Entering directory `/home/tecnotree/sftp-invoice-uploader/node_modules/kafka-node/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/home/tecnotree/sftp-invoice-uploader/node_modules/kafka-node/node_modules/snappy/build'
underscore@1.8.3 node_modules/underscore

bunyan-prettystream@0.1.3 node_modules/bunyan-prettystream

async@1.5.2 node_modules/async

stream@0.0.2 node_modules/stream
└── emitter-component@1.1.1

through2@2.0.1 node_modules/through2
├── xtend@4.0.1
└── readable-stream@2.0.6 (string_decoder@0.10.31, inherits@2.0.1, util-deprecate@1.0.2, process-nextick-args@1.0.7, core-util-is@1.0.2, isarray@1.0.0)

ssh2@0.4.15 node_modules/ssh2
├── readable-stream@1.0.34 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.2)
└── ssh2-streams@0.0.23 (streamsearch@0.1.2, asn1@0.2.3)

scp2@0.3.0 node_modules/scp2
├── async@0.9.2
├── lodash@2.4.2
└── glob@4.0.6 (inherits@2.0.1, graceful-fs@3.0.8, once@1.3.3, minimatch@1.0.0)

mongodb@2.2.5 node_modules/mongodb
├── es6-promise@3.0.2
├── readable-stream@1.0.31 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.2)
└── mongodb-core@2.0.7 (require_optional@1.0.0, bson@0.5.2)

bunyan@1.8.1 node_modules/bunyan
├── safe-json-stringify@1.0.3
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.5)
└── dtrace-provider@0.6.0 (nan@2.4.0)

moment@2.14.1 node_modules/moment

kafka-node@0.2.30 node_modules/kafka-node
├── buffer-crc32@0.2.5
├── retry@0.6.1
├── node-uuid@1.4.7
├── debug@2.2.0 (ms@0.7.1)
├── buffermaker@1.2.0 (long@1.1.2)
├── node-zookeeper-client@0.2.2 (async@0.2.10, underscore@1.4.4)
├── binary@0.3.0 (buffers@0.1.1, chainsaw@0.1.0)
├── lodash@3.10.1
└── snappy@4.1.2 (bindings@1.2.1, nan@2.2.0, node-gyp@3.2.1)
```

**Comment by johnshumon** [comment]
@kesla I think you should make a dependency documentation for this. :)

**Comment by kesla** [comment]
@johnshumon Perhaps you could open a pull request adding documentation about tthis?

**Comment by fzahabian** [comment]
I am also seeing this issue on OSX (v 10.10.5), Xcode (v 7.2.1), npm (v 3.10.7), and node (v v4.4.3) . I am also able to install other compiled packages such as  leveldown.  

```
la-ol-2217:snappy faraz.zahabian$ npm install snappy 

> snappy@5.0.5 install /Users/faraz.zahabian/dev/playground/snappy/node_modules/snappy
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2016-09-20 11:10:30.051 xcodebuild[70692:9071016] Error initializing toolchains: Error Domain=DVTToolchainErrorDomain Code=1 "The operation couldn’t be completed. (DVTToolchainErrorDomain error 1.)" UserInfo=0x7fb908f07a50 {NSUnderlyingError=0x7fb908f05580 "couldn't register toolchain <DVTToolchain:0x7fb908f067a0:'com.apple.dt.toolchain.XcodeDefault':'(null)'>"}
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
clang: warning: no such sysroot directory: '/Developer/SDKs/MacOSX10.6.sdk'
../deps/snappy/snappy-1.1.2/snappy-sinksource.cc:29:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
1 error generated.
make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/faraz.zahabian/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/faraz.zahabian/.nvm/versions/node/v4.4.3/bin/node" "/Users/faraz.zahabian/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/faraz.zahabian/dev/playground/snappy/node_modules/snappy
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/faraz.zahabian/dev/playground/snappy/package.json'
npm WARN snappy No description
npm WARN snappy No repository field.
npm WARN snappy No README data
npm WARN snappy No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/faraz.zahabian/.nvm/versions/node/v4.4.3/bin/node" "/Users/faraz.zahabian/.nvm/versions/node/v4.4.3/bin/npm" "install" "snappy"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! snappy@5.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by Alexintosh** [comment]
Any news on this?

**Comment by urbanvikingr** [comment]
node-gyp rebuild fails on my machine.

My environment is:
```
macOS 10.11.6
python 2.7.13
gcc Apple LLVM version 8.0.0 (clang-800.0.42.1)
node 7.9.0
npm 4.2
```

The error is:
```
CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
clang: error: no such file or directory: 'dan/.node-gyp/7.7.2/include/node'
clang: error: no such file or directory: 'dan/.node-gyp/7.7.2/src'
clang: error: no such file or directory: 'dan/.node-gyp/7.7.2/deps/uv/include'
clang: error: no such file or directory: 'dan/.node-gyp/7.7.2/deps/v8/include'
make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o] Error 1
```

Not sure why it is looking for folder 'dan' when my user name is 'jensen dan'.

**Comment by rihannarickeminem** [comment]
also got in `snappy@5.0.5 install: `node-gyp rebuild`

**Comment by shridharmanvi** [comment]
Same issue: `Error: snappy@5.0.5 install: `node-gyp rebuild``
I am using MacOS

**Comment by kesla** [comment]
@shridharmanvi  on node 4? Also latest version of snappy is 6, any difference? We don't run "node-gyp rebuild" anymore.

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!

**Comment by dearpeach** [comment]
I use snappy(6.1.1), but cent0s6 can't compile snappy, how does you guys do if not update glibc version
