### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by sqvcnet** [kesla/node-snappy#93]
NAN_METHOD(CompressSync) {
  std::string *input;
  std::string dst;

  if (node::Buffer::HasInstance(info[0]->ToObject())) {
    v8::Local<v8::Object> object = info[0]->ToObject();
    size_t length = node::Buffer::Length(object);
    const char *data = node::Buffer::Data(object);
    input = new std::string(data, length);
  } else {
    v8::String::Utf8Value param1(info[0]->ToString());
    input = new std::string(*param1);
  }

  snappy::Compress(input->data(), input->length(), &dst);

  v8::Local<v8::Object> res = Nan::NewBuffer(dst.length()).ToLocalChecked();
  memcpy(node::Buffer::Data(res), dst.c_str(), dst.length());

  info.GetReturnValue().Set(res);
}

    input = new std::string(data, length);
    input = new std::string(*param1); 

no delete for new in this function, lead to memory leak on our production server, we use xcode and instruments analyze this bug and locate to this position.

**Comment by kesla** [comment]
@sqvcnet nice found, thanks. I'd gladly accept a PR to fix this - but otherwise I guess I'll come up with something in a few days.

**Comment by sqvcnet** [comment]
snappy::Compress(input->data(), input->length(), &dst);
+ delete input;

**Comment by sqvcnet** [comment]
snappy::Compress(input->data(), input->length(), &dst);
  delete input;

**Comment by sqvcnet** [comment]
I have created a pull request for you, please merge it if you think it's ok.
